export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  image: string; // Path to the image inside public/images/shop
}

// Updated sample products data (with .png extensions)
export const sampleProducts: Product[] = [
  {
    id: 1,
    name: 'cashmere-scarf',
    category: 'Accessories',
    price: 49.99,
    image: 'images/shop/cashmere-scarf.png',
  },
  {
    id: 2,
    name: 'casual-summer-dress',
    category: 'Women',
    price: 29.99,
    image: 'images/shop/casual-summer-dress.png',
  },
  {
    id: 3,
    name: 'chic-skirt',
    category: 'Women',
    price: 19.99,
    image: 'images/shop/chic-skirt.png',
  },
  {
    id: 4,
    name: 'chino-pants',
    category: 'Men',
    price: 39.99,
    image: 'images/shop/chino-pants.png',
  },
  {
    id: 5,
    name: 'classic-fit-oxford-shirt',
    category: 'Men',
    price: 25.99,
    image: 'images/shop/classic-fit-oxford-shirt.png',
  },
  {
    id: 6,
    name: 'classic-fit-tee',
    category: 'Men',
    price: 15.99,
    image: 'images/shop/classic-fit-tee.png',
  },
  {
    id: 7,
    name: 'comfortable-jeans',
    category: 'Men',
    price: 39.99,
    image: 'images/shop/comfortable-jeans.png',
  },
  {
    id: 8,
    name: 'cotton-blend-hoodie',
    category: 'Women',
    price: 34.99,
    image: 'images/shop/cotton-blend-hoodie.png',
  },
  {
    id: 9,
    name: 'crew-neck-t-shirt',
    category: 'Men',
    price: 19.99,
    image: 'images/shop/crew-neck-t-shirt.png',
  },
  {
    id: 10,
    name: 'elegant-evening-gown',
    category: 'Women',
    price: 99.99,
    image: 'images/shop/elegant-evening-gown.png',
  },
  {
    id: 11,
    name: 'elegant-gold-necklace',
    category: 'Accessories',
    price: 79.99,
    image: 'images/shop/elegant-gold-necklace.png',
  },
  {
    id: 12,
    name: 'fedora-hat',
    category: 'Accessories',
    price: 24.99,
    image: 'images/shop/fedora-hat.png',
  },
  {
    id: 13,
    name: 'joggers',
    category: 'Men',
    price: 29.99,
    image: 'images/shop/joggers.png',
  },
  {
    id: 14,
    name: 'leather-crossbody-bag',
    category: 'Accessories',
    price: 79.99,
    image: 'images/shop/leather-crossbody-bag.png',
  },
  {
    id: 15,
    name: 'lightweight-bomber-jacket',
    category: 'Men',
    price: 59.99,
    image: '/images/shop/lightweight-bomber-jacket.png',
  },
  {
    id: 16,
    name: 'performance-shorts',
    category: 'Men',
    price: 19.99,
    image: 'images/shop/performance-shorts.png',
  },
  {
    id: 17,
    name: 'relaxed-fit-jeans',
    category: 'Men',
    price: 39.99,
    image: 'images/shop/relaxed-fit-jeans.png',
  },
  {
    id: 18,
    name: 'silk-scarf-with-floral-print',
    category: 'Accessories',
    price: 59.99,
    image: 'images/shop/silk-scarf-with-floral-print.png',
  },
  {
    id: 19,
    name: 'slim-fit-chinos',
    category: 'Men',
    price: 35.99,
    image: 'images/shop/slim-fit-chinos.png',
  },
  {
    id: 20,
    name: 'slim-fit-jeans',
    category: 'Men',
    price: 45.99,
    image: '/images/shop/slim-fit-jeans.png',
  },
  {
    id: 21,
    name: 'statement-earrings',
    category: 'Accessories',
    price: 29.99,
    image: 'images/shop/statement-earrings.png',
  },
  {
    id: 22,
    name: 'stretch-polo',
    category: 'Men',
    price: 22.99,
    image: 'images/shop/stretch-polo.png',
  },
  {
    id: 23,
    name: 'stylish-work-blouse',
    category: 'Women',
    price: 34.99,
    image: 'images/shop/stylish-work-blouse.png',
  },
  {
    id: 24,
    name: 'sweatpants',
    category: 'Men',
    price: 19.99,
    image: 'images/shop/sweatpants.png',
  },
  {
    id: 25,
    name: 'training-pants',
    category: 'Men',
    price: 24.99,
    image: 'images/shop/training-pants.png',
  },
  {
    id: 26,
    name: 'versatile-cardigan',
    category: 'Women',
    price: 39.99,
    image: 'images/shop/versatile-cardigan.png',
  },
  {
    id: 27,
    name: 'wide-brimmed-sun-hat',
    category: 'Accessories',
    price: 19.99,
    image: 'images/shop/wide-brimmed-sun-hat.png',
  },
  {
    id: 28,
    name: 'windbreaker',
    category: 'Men',
    price: 49.99,
    image: 'images/shop/windbreaker.png',
  },
  {
    id: 29,
    name: 'woven-belt',
    category: 'Accessories',
    price: 14.99,
    image: 'images/shop/woven-belt.png',
  },
];
